namespace EasyStateful.Runtime
{   
    public enum Ease
    {
        Unset = 0,
        Linear = 1,
        InSine = 2,
        OutSine = 3,
        InOutSine = 4,
        InQuad = 5,
        OutQuad = 6,
        InOutQuad = 7,
        InCubic = 8,
        OutCubic = 9,
        InOutCubic = 10,
        InQuart = 11,
        OutQuart = 12,
        InOutQuart = 13,
        InQuint = 14,
        OutQuint = 15,
        InOutQuint = 16,
        InExpo = 17,
        OutExpo = 18,
        InOutExpo = 19,
        InCirc = 20,
        OutCirc = 21,
        InOutCirc = 22,
        InElastic = 23,
        OutElastic = 24,
        InOutElastic = 25,
        InBack = 26,
        OutBack = 27,
        InOutBack = 28,
        InBounce = 29,
        OutBounce = 30,
        InOutBounce = 31,
        Flash = 32, // changes instantly midway
        InFlash = 33, // always 1
        OutFlash = 34, // 0, but jumps to 1 at end
        User00 = 35,
        User01 = 36,
        User02 = 37,
        User03 = 38,
        User04 = 39,
        User05 = 40,
        User06 = 41,
        User07 = 42,
        User08 = 43,
        User09 = 44,
    }
}